"""Communication Drafting Agent: an internal-only coordinator note.

Also the deterministic-template fallback used whenever the LLM layer is
off, budget-exhausted, or fails schema validation -- output shape stays
stable regardless of narrative_source.
"""

from __future__ import annotations

from typing import Any


def draft(patient: dict[str, Any], intervals: dict, risk: dict, recommendation: str) -> str:
    return (
        f"Internal note – {patient['mrn']} ({patient['first_name']} {patient['last_name']})\n"
        f"Diagnosis: {patient['diagnosis_type']} | Stage: {patient['stage']} | Pathway: {patient['treatment_modality_pathway']}\n"
        f"Priority: {patient['priority_level']} | Risk: {risk['risk_level']} ({risk['risk_score']}) | Payer: {patient['payer_type']}\n"
        f"Current status: {patient['scheduling_status']} | Coordinator: {patient['assigned_coordinator_name']}\n"
        f"Primary bottleneck: {intervals['primary_bottleneck']}\n"
        f"Projected / actual diagnosis-to-treatment: ~{risk['projected_days']} days\n"
        f"Recommended action: {recommendation}\n"
        f"— Generated by Oncology Pipeline (deterministic template; human review required)"
    )
